#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

echo "--- Installing prerequisites"
pip install nodeenv
node=$(nodeenv --list 2>&1 | tr '\t' '\n' | grep -E '^12' | tail -n 1)

nodeenv --node="$node" /tmp/node

# shellcheck disable=SC1091
/tmp/node/bin/npm install jest jsdom

echo "--- Running Jest"
echo "{\"scripts\":{\"test\": \"jest\"}}" > package.json
/tmp/node/bin/npm test
