#!/usr/bin/env bash
set -euo pipefail

# automatically open the log output group if there's an error
trap 'echo "^^^ +++"' ERR

echo "--- Installing prerequisites"
node=$(nodeenv --list 2>&1 | tr '\t' '\n' | grep -E '^12' | tail -n 1)

nodeenv --node="$node" /tmp/node
/tmp/node/bin/npm install -g jest jsdom@9.9.1
echo "{}" > package.json

echo "--- Running Jest"
jest
